### ISSUE TITLE
Enforce rules as described by GitPraxis.md

### ISSUE THREAD

**Issue by AlexTelon** [AlexTelon/FlexiCharge-Org#79]
_(btw we should add a version to the GitPraxis.md file in case we ever make "breaking changes", it would be useful to know which version I am applying my changed based on at a glance without having to be a detective and look at dates)_

Leon created https://github.com/AlexTelon/FlexiExample/ and then transfered ownership to me. It has 2 rulesets that I need to apply for all repos since Im the owner Im the only one who can do that.

I need to enforce this in the following repos

- [x] [BMS](https://github.com/AlexTelon/FlexiCharge-BMS)  
- [x] [Backend](https://github.com/AlexTelon/FlexiCharge-Backend)
- [x] [Charge-station-plus](https://github.com/AlexTelon/FlexiCharge-Charge-station-plus)
- [x] [Admin-GUI](https://github.com/AlexTelon/FlexiCharge-Admin-GUI)
- [x] [My-pages](https://github.com/AlexTelon/FlexiCharge-My-pages)
- [x] [Cross-Platform](https://github.com/AlexTelon/FlexiCharge-Cross-Platform)
- [x] [Android](https://github.com/AlexTelon/FlexiCharge-Android)

Skipping these as they are not used?
 * [iOS](https://github.com/AlexTelon/FlexiCharge-iOS)
 * [Test-and-integration](https://github.com/AlexTelon/FlexiCharge-Test-and-integration)

Skipping this since we dont build anything from this repo, its only for documentation.
 * [Org](https://github.com/AlexTelon/FlexiCharge-Org)

(**todo** we should probablye update the GitPraxis.md document to note that the Org repo is exempt)

**Comment by AlexTelon** [comment]
@ecle20yy @ljungqvistaxel to enforce this in your BMS repo I changed `master` to `main`.

Tell me if you notice any issues with how I applied this to your repo. I will wait a little bit before I apply the rules to other repos. Like for a day at most. But would want some feedback if things works as expected before I do this manually on all other repos.

Also I have not added Ellen our build master to have any exemptions. I did not find a way to add a individual directly. Only roles and roles seem to only be possible to manage if one has a organization. See #73.

Would this cause issues? Every process must not be enforced by tooling. We can have a policy that she is the only one who can accept PR's to main even if technically all collaborators in the repo can do so.

**Comment by AlexTelon** [comment]
Multiple teams have branches with the wrong names. Im not sure if we should ask them to fix their branch names first then I can apply these changes?
Because if I apply these changes first then the [Android](https://github.com/AlexTelon/FlexiCharge-Android/branches) team not be able to rename Dev to dev for instance

**Comment by ecle20yy** [comment]
I will tell my squad to begin working with the reporitory to see if they encounter any issues.

**Comment by ecle20yy** [comment]
I have tested the new rules. See [this issue](https://github.com/AlexTelon/FlexiCharge-BMS/issues/41) for what I tried. Did not try to push to main though, but other than that the rules seems to work.

**Comment by foal20ym** [comment]
> Multiple teams have branches with the wrong names. Im not sure if we should ask them to fix their branch names first then I can apply these changes?
> Because if I apply these changes first then the [Android](https://github.com/AlexTelon/FlexiCharge-Android/branches) team might not be able to rename Dev to dev for instance. I would then have to do so manually.

We have now renamed the Dev branch to 'dev'. I give you a green light to apply the changes! 👍

**Comment by AlexTelon** [comment]
Great. I will apply these rules on the remaining repos tomorrow then

**Comment by AlexTelon** [comment]
Have applied to all teams now.
