### ISSUE TITLE
Not possible to merge to main

### ISSUE THREAD

**Issue by AlexTelon** [AlexTelon/FlexiCharge-Org#89]
I mentioned this in #79: 

_"Also I have not added @ellencarlsson our build master to have any exemptions. I did not find a way to add a individual directly. Only roles and roles seem to only be possible to manage if one has a organization. See https://github.com/AlexTelon/FlexiCharge-Org/issues/73._

_Would this cause issues? Every process must not be enforced by tooling. We can have a policy that she is the only one who can accept PR's to main even if technically all collaborators in the repo can do so."_

#73 would be one possible way to solve this. But I wont have time to look into this now.

Could we relax the enforced rules to allow updates to main? Like the Build Master is still the only one allowed to do it. But technically others could do so as well.

@ellencarlsson @Lillenooben @ecle20yy

**Comment by ellencarlsson** [comment]
<img width="1284" alt="Skärmavbild 2023-09-18 kl  08 58 10" src="https://github.com/AlexTelon/FlexiCharge-Org/assets/98748113/95c951fc-88dc-400b-81f4-ef34a99908de">

**Comment by ecle20yy** [comment]
The only reason I would have against this is that during a new PR, the text telling you which branch you're targeting is quite small and could be missed. So feature branches destined for `dev` could end up all the way in main if both creator of the PR and the approver misses this part.
But perhaps a PR template with a "confirm correct branch is targeted" checkbox or something could help catch that?

**Comment by AlexTelon** [comment]
_"But perhaps a PR template with a "confirm correct branch is targeted" checkbox or something could help catch that?"_

I really like this suggestion. If we find out that we actually have issues with this, meaning people merge to the wrong place, we can look into improving the process. But we can live with the risk I think. Its always possible to revert for instance if something actually went wrong. 

I mean we could probably add a github action that checks if the PR to main was approved by ellen and if not fail it.
Or use a hack where ellen is marked as the only codeowners and enfore codeowners in PR's to main. 

So suggestion is

1. @AlexTelon allows updates to the `main` branch in all repos. (I could do this today if you agree)
2. @ellencarlsson  and @Lillenooben  create/delegate so that a PR template is created that then all squads can add to their repo for the next sprint?


Sounds good?

**Comment by AlexTelon** [comment]
Ok will update these repos and once a new issue has been created regarding point 2 above we can close this issue. @ellencarlsson can you create an issue for the addition of a PR template and reference this issue?

- [x] [BMS](https://github.com/AlexTelon/FlexiCharge-BMS)  
- [] [Backend](https://github.com/AlexTelon/FlexiCharge-Backend)
- [] [Charge-station-plus](https://github.com/AlexTelon/FlexiCharge-Charge-station-plus)
- [] [Admin-GUI](https://github.com/AlexTelon/FlexiCharge-Admin-GUI)
- [] [My-pages](https://github.com/AlexTelon/FlexiCharge-My-pages)
- [] [Cross-Platform](https://github.com/AlexTelon/FlexiCharge-Cross-Platform)
- [] [Android](https://github.com/AlexTelon/FlexiCharge-Android)

**Comment by AlexTelon** [comment]
Note for the future. I'm happy to do more changes to the rules if you need or wish to try something else out. Just provide me with a clear instruction or which setting you wish changed and a checklist like the one above of which repos to change and it will probably only take me a few minutes.

As long as the instructions are clear and that I see that the build master approves of it.

**Comment by ellencarlsson** [comment]
> Ok will update these repos and once a new issue has been created regarding point 2 above we can close this issue. @ellencarlsson can you create an issue for the addition of a PR template and reference this issue?
> 
> * [x]  [BMS](https://github.com/AlexTelon/FlexiCharge-BMS)
> * [x]  [Backend](https://github.com/AlexTelon/FlexiCharge-Backend)
> * [x]  [Charge-station-plus](https://github.com/AlexTelon/FlexiCharge-Charge-station-plus)
> * [x]  [Admin-GUI](https://github.com/AlexTelon/FlexiCharge-Admin-GUI)
> * [x]  [My-pages](https://github.com/AlexTelon/FlexiCharge-My-pages)
> * [x]  [Cross-Platform](https://github.com/AlexTelon/FlexiCharge-Cross-Platform)
> * [x]  [Android](https://github.com/AlexTelon/FlexiCharge-Android)

**Comment by ellencarlsson** [comment]
> Ok will update these repos and once a new issue has been created regarding point 2 above we can close this issue. @ellencarlsson can you create an issue for the addition of a PR template and reference this issue?
> 
> * [x]  [BMS](https://github.com/AlexTelon/FlexiCharge-BMS)
> * [x]  [Backend](https://github.com/AlexTelon/FlexiCharge-Backend)
> * [x]  [Charge-station-plus](https://github.com/AlexTelon/FlexiCharge-Charge-station-plus)
> * [x]  [Admin-GUI](https://github.com/AlexTelon/FlexiCharge-Admin-GUI)
> * [x]  [My-pages](https://github.com/AlexTelon/FlexiCharge-My-pages)
> * [x]  [Cross-Platform](https://github.com/AlexTelon/FlexiCharge-Cross-Platform)
> * [x]  [Android](https://github.com/AlexTelon/FlexiCharge-Android)

yes I can do that!!
